In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=pd.read_csv("titanic_dataset.csv")
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
df=df.drop(columns=["PassengerId","Name","Ticket","Fare","Cabin"],axis=1)

In [6]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  34.5      0      0        Q
1         1       3  female  47.0      1      0        S
2         0       2    male  62.0      0      0        Q
3         0       3    male  27.0      0      0        S
4         1       3  female  22.0      1      1        S

In [7]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

In [8]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [9]:
df["Embarked"].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [10]:
df.replace({"Sex":{"male":0,"female":1}},inplace=True)
df.replace({"Embarked": {'S':0,'C':1,'Q':2}},inplace=True)

In [11]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    0  34.5      0      0         2
1         1       3    1  47.0      1      0         0
2         0       2    0  62.0      0      0         2
3         0       3    0  27.0      0      0         0
4         1       3    1  22.0      1      1         0

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [14]:
data=df.values
X=data[:,1:]
Y=data[:,0]

In [15]:
X

array([[ 3.        ,  0.        , 34.5       ,  0.        ,  0.        ,
         2.        ],
       [ 3.        ,  1.        , 47.        ,  1.        ,  0.        ,
         0.        ],
       [ 2.        ,  0.        , 62.        ,  0.        ,  0.        ,
         2.        ],
       ...,
       [ 3.        ,  0.        , 38.5       ,  0.        ,  0.        ,
         0.        ],
       [ 3.        ,  0.        , 30.27259036,  0.        ,  0.        ,
         0.        ],
       [ 3.        ,  0.        , 30.27259036,  1.        ,  1.        ,
         1.        ]])

In [16]:
Y

array([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [28]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [32]:
# using k-nearest neighbour
from sklearn.neighbors import KNeighborsClassifier
n= KNeighborsClassifier(n_neighbors=3)
n.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=3)

In [33]:
Y_pred = n.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]]


In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(Y_test, Y_pred)
print("confusion matrix : ")
print(cm)
print("Accuracy:")
print(accuracy_score(Y_test, Y_pred))
print("classification report : ")
print(classification_report(Y_test, Y_pred))

confusion matrix : 
[[53  0]
 [10 21]]
Accuracy:
0.8809523809523809
classification report : 
              precision    recall  f1-score   support

         0.0       0.84      1.00      0.91        53
         1.0       1.00      0.68      0.81        31

    accuracy                           0.88        84
   macro avg       0.92      0.84      0.86        84
weighted avg       0.90      0.88      0.87        84



In [38]:
X

array([[ 3.        ,  0.        , 34.5       ,  0.        ,  0.        ,
         2.        ],
       [ 3.        ,  1.        , 47.        ,  1.        ,  0.        ,
         0.        ],
       [ 2.        ,  0.        , 62.        ,  0.        ,  0.        ,
         2.        ],
       ...,
       [ 3.        ,  0.        , 38.5       ,  0.        ,  0.        ,
         0.        ],
       [ 3.        ,  0.        , 30.27259036,  0.        ,  0.        ,
         0.        ],
       [ 3.        ,  0.        , 30.27259036,  1.        ,  1.        ,
         1.        ]])

In [39]:
x.shape

NameError: ignored

In [41]:
Y

array([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [42]:
# using decition tree

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [43]:


from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=0)

In [44]:
Y_pred = n.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [45]:
cm = confusion_matrix(Y_test, Y_pred)
print("confusion matrix : ")
print(cm)
print("Accuracy:")
print(accuracy_score(Y_test, Y_pred))
print("classification report : ")
print(classification_report(Y_test, Y_pred))

confusion matrix : 
[[49  1]
 [ 5 29]]
Accuracy:
0.9285714285714286
classification report : 
              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94        50
         1.0       0.97      0.85      0.91        34

    accuracy                           0.93        84
   macro avg       0.94      0.92      0.92        84
weighted avg       0.93      0.93      0.93        84

